# =========================================================================
# Size Report Utilities
# =========================================================================

function(parse_size_file file prefix)
    file(READ "${file}" CONTENT)
    string(REGEX MATCH "[ \t]*[0-9]+[ \t]+[0-9]+[ \t]+[0-9]+" LINE "${CONTENT}")
    string(STRIP "${LINE}" LINE)
    string(REGEX REPLACE "[ \t]+" ";" VALUES "${LINE}")
    list(GET VALUES 0 TEXT)
    list(GET VALUES 1 DATA)
    list(GET VALUES 2 BSS)
    set(${prefix}_TEXT ${TEXT} PARENT_SCOPE)
    set(${prefix}_DATA ${DATA} PARENT_SCOPE)
    set(${prefix}_BSS ${BSS} PARENT_SCOPE)
endfunction()

function(compute_size_totals)
    math(EXPR FLASH_TOTAL "${BPRIM_TEXT} + ${BPRIM_DATA} + ${BSEC_TEXT} + ${BSEC_DATA} + ${APP_TEXT} + ${APP_DATA}")
    math(EXPR RAM_TOTAL   "${BPRIM_DATA} + ${BPRIM_BSS} + ${BSEC_DATA} + ${BSEC_BSS} + ${APP_DATA} + ${APP_BSS}")
    math(EXPR FLASH_USAGE_PERCENT "(${FLASH_TOTAL} * 100) / ${MCU_FLASH_LIMIT}")
    math(EXPR RAM_USAGE_PERCENT   "(${RAM_TOTAL} * 100) / ${MCU_RAM_LIMIT}")

    set(FLASH_TOTAL ${FLASH_TOTAL} PARENT_SCOPE)
    set(RAM_TOTAL ${RAM_TOTAL} PARENT_SCOPE)
    set(FLASH_USAGE_PERCENT ${FLASH_USAGE_PERCENT} PARENT_SCOPE)
    set(RAM_USAGE_PERCENT ${RAM_USAGE_PERCENT} PARENT_SCOPE)
endfunction()

function(print_size_summary)
    message(STATUS "")
    message(STATUS "┌────────────────────────────┬──────────────┬────────────────────────────────────────┐")
    message(STATUS "│ Section                    │ Size (bytes) │ Description Platform ${MCU_MODEL}     │")
    message(STATUS "├────────────────────────────┼──────────────┼────────────────────────────────────────┤")
    message(STATUS "│ Boot Prim .text            │ ${BPRIM_TEXT}        │ Code (in FLASH)                        │")
    message(STATUS "│ Boot Prim .data            │ ${BPRIM_DATA}         │ Initialized data (RAM, stored in FLASH)│")
    message(STATUS "│ Boot Prim .bss             │ ${BPRIM_BSS}         │ Uninitialized data (RAM)              │")
    message(STATUS "│ Boot Sec .text             │ ${BSEC_TEXT}        │ Code (in FLASH)                        │")
    message(STATUS "│ Boot Sec .data             │ ${BSEC_DATA}         │ Initialized data (RAM, stored in FLASH)│")
    message(STATUS "│ Boot Sec .bss              │ ${BSEC_BSS}         │ Uninitialized data (RAM)              │")
    message(STATUS "│ App .text                  │ ${APP_TEXT}        │ Code (in FLASH)                        │")
    message(STATUS "│ App .data                  │ ${APP_DATA}         │ Initialized data (RAM, stored in FLASH)│")
    message(STATUS "│ App .bss                   │ ${APP_BSS}         │ Uninitialized data (RAM)              │")
    message(STATUS "├────────────────────────────┼──────────────┼────────────────────────────────────────┤")
    message(STATUS "│ FLASH total                │ ${FLASH_TOTAL}       │ .text + .data                          │")
    message(STATUS "│ RAM total                  │ ${RAM_TOTAL}        │ .data + .bss                           │")
    message(STATUS "└────────────────────────────┴──────────────┴────────────────────────────────────────┘")

    message(STATUS "FLASH usage: ${FLASH_TOTAL} bytes (${FLASH_USAGE_PERCENT}%)")
    message(STATUS "RAM usage: ${RAM_TOTAL} bytes (${RAM_USAGE_PERCENT}%)")

    if(FLASH_USAGE_PERCENT GREATER 90)
        message(FATAL_ERROR "FLASH usage exceeds 90% (${FLASH_USAGE_PERCENT}%) — build failed.")
    endif()
    if(RAM_USAGE_PERCENT GREATER 90)
        message(FATAL_ERROR "RAM usage exceeds 90% (${RAM_USAGE_PERCENT}%) — build failed.")
    endif()
endfunction()

function(write_size_json output_path)
    set(JSON "{\n")
    string(APPEND JSON "  \"bootloader_primary\": {\n    \"text\": ${BPRIM_TEXT},\n    \"data\": ${BPRIM_DATA},\n    \"bss\": ${BPRIM_BSS}\n  },\n")
    string(APPEND JSON "  \"bootloader_secondary\": {\n    \"text\": ${BSEC_TEXT},\n    \"data\": ${BSEC_DATA},\n    \"bss\": ${BSEC_BSS}\n  },\n")
    string(APPEND JSON "  \"application\": {\n    \"text\": ${APP_TEXT},\n    \"data\": ${APP_DATA},\n    \"bss\": ${APP_BSS}\n  },\n")
    string(APPEND JSON "  \"combined\": {\n    \"flash\": ${FLASH_TOTAL},\n    \"ram\": ${RAM_TOTAL},\n    \"flash_usage_percent\": ${FLASH_USAGE_PERCENT},\n    \"ram_usage_percent\": ${RAM_USAGE_PERCENT}\n  }\n")
    string(APPEND JSON "}\n")
    file(WRITE "${output_path}" "${JSON}")
    message(STATUS "Size data written to: ${output_path}")
    message(STATUS "")
endfunction()

